title: Holy Sung's Homepage
page-top-title: Shengjie SONG
top-section-bg-text: Code Path and Advanced Learning
home-subtitle: 宋圣洁(Mr. Holy Sung)
copyright-text: '&copy; 宋圣洁. All Rights Reserved.'
highlighter: rouge
